### PR TITLE
Update to containerd 1.2.2

### PR DESCRIPTION
**Pull request by Random-Liu**
Based on https://github.com/google/gvisor-containerd-shim/pull/13.

This PR:
1) Update containerd to 1.2.2 to pick up fixes like https://github.com/containerd/containerd/pull/2762;
2) Port https://github.com/containerd/containerd/pull/2803. Actually this is not necessary, but it helps it easy to port future fixes.

### CODE REVIEW

**Comment by ianlewis** [comment]
@Random-Liu 
We may want to do something at some point to alleviate the need to port changes from containerd all the time. Maybe some kind of better API or library for shims to use? Do other shims depend on containerd in this way?

**Comment by Random-Liu** [comment]
> We may want to do something at some point to alleviate the need to port changes from containerd all the time. Maybe some kind of better API or library for shims to use? Do other shims depend on containerd in this way?

I think the containerd-shim code is expected to be eventually very stable, the port change cases should be less and less. So I'm currently not too worry about that.

And it is good that we can get the same bug fix from containerd-shim, because it is more battle tested. :)

**Comment by Random-Liu** [comment]
Merge based on https://github.com/google/gvisor-containerd-shim/pull/14#issuecomment-458406074

**Comment by ianlewis** [comment]
> > We may want to do something at some point to alleviate the need to port changes from containerd all the time. Maybe some kind of better API or library for shims to use? Do other shims depend on containerd in this way?
> 
> I think the containerd-shim code is expected to be eventually very stable, the porting change cases should be less and less. So I'm currently not too worry about that.
> 
> And it is good that we can get the same bug fix from containerd-shim, because it is more battle tested. :)

Yah, I'm just thinking I'd rather we were able to vendor that code as a library rather than merge it :)

**Pull request merged**
